version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered build phase
      - mvn install
artifacts:
  files:
    - target/valuePal-java-0.0.1-SNAPSHOT.jar
