version: 0.2
phases:
  pre_build:
    commands:
      - echo Entered pre-build phase
  build:
    commands:
      - echo Entered build phase
      - mvn package
  post_build:
    commands:
      - echo build completed on 'date'
artifacts:
  files:
    - target/valuePal-java-0.0.1-SNAPSHOT.jar